### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [bresan/android_tmdb_clean_architecture#1]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by rodrigobressan** [comment]
Hey @oleksiyp,

Thanks for the suggestion, for sure I will be looking to use it into new projects in the future, since now I am quite busy with some other side projects.

Hope you have a nice day and a great end of year!

Best regards,
Rodrigo Bresan
